#!/usr/bin/env bash
# encoding: UTF-8
#
# Created by Wannes Meert on 2011-12-20.
# Copyright (c) 2011-2012 KU Leuven. All rights reserved.

VERSION='rmvim version 1.0.1 (2012-06-03)'

HOST=localhost
PORT=52699
VERBOSE=0
FILEPATH=""
USE_HOSTNAME_FOR_RHOST=0
CUSTOM_RHOST_NAME=""

USAGE="Usage: rmvim [-vVhH] [-p portnumber] -c [name] file"

while getopts vVhHp:c: o
do  case "$o" in
    v)      VERBOSE=1;;
    p)      PORT="$OPTARG";;
    V)      echo "$VERSION"
            exit 1;;
    h)      echo "$USAGE" >&2
            exit 1;;
    H)      USE_HOSTNAME_FOR_RHOST=1;;
    c)      CUSTOM_RHOST_NAME="$OPTARG";;
    [?])    echo "$USAGE" >&2
            exit 1;;
    esac
done
shift $(($OPTIND-1))
FILEPATH="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"

# VALUES
LHOST=${SSH_CONNECTION%% *}
if [ -n "$CUSTOM_RHOST_NAME" ]; then
  RHOST="$CUSTOM_RHOST_NAME"
elif [ $USE_HOSTNAME_FOR_RHOST -eq 1 ]; then
  RHOST=`hostname -f`
else
  RHOST=${SSH_CONNECTION#* }
  RHOST=${RHOST#* }
  RHOST=${RHOST%% *} # Get 3rd argument, separated by spaces
  if [ -z "$RHOST" ]; then
    RHOST=$HOST
  fi
fi

# MAIN
if [ $VERBOSE -eq 1 ]; then
    echo "RHOST=$RHOST"
fi

if which nc > /dev/null; then
    echo -e "open:scp://$RHOST/$FILEPATH" | nc "$HOST" "$PORT"
else
    exec 3<>/dev/tcp/$HOST/$PORT # Open tcp connection and assign fd 3 to it
    echo -e "open:scp://$RHOST/$FILEPATH" >&3
    exec 3>&- # Close fd 3
fi

: <<=cut
=pod

=head1 RMVIM

rmvim - Start local mvim instance from a remote server.

=head1 DESCRIPTION

This script starts mvim on your local machine and opens the file given as
argument (or the current directory if no argument is given).

It is based on the idea of rmate included with TextMate 2.0
(see www.macromates.com).

To be used in conjuntion with rmvim_listener.

=head1 USAGE

rmvim [-vVhH] [-p portnumber] -c [name] file

=over 8

=item -v Verbose

=item -V Version

=item -h Help

=item -H Use hostname instead of IP in SSH command

=item -p Portnumber (default: 52699)

=item -c Name (use provided name instead of IP in SSH command)

=back

=head1 AUTHOR

Wannes Meert

http://people.cs.kuleuven.be/wannes.meert

=head1 LICENSE

FreeBSD License

Copyright (c) 2011-2012, Wannes Meert (KU Leuven). All rights reserved.

=cut

#vim: ft=SH expandtab

